// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id,
    channel_id,
    author_id,
    content
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, channel_id, author_id, content, created_at, updated_at
`

type CreateMessageParams struct {
	ID        int64  `json:"id"`
	ChannelID int64  `json:"channel_id"`
	AuthorID  int64  `json:"author_id"`
	Content   string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ChannelID,
		arg.AuthorID,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
