// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id,
    channel_id,
    author_id,
    content
) VALUES (
    $1,
    $2,
    $3,
    $4
) RETURNING id, channel_id, author_id, content, created_at, updated_at
`

type CreateMessageParams struct {
	ID        int64  `json:"id"`
	ChannelID int64  `json:"channel_id"`
	AuthorID  int64  `json:"author_id"`
	Content   string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ChannelID,
		arg.AuthorID,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelMessages = `-- name: GetChannelMessages :many
SELECT id, channel_id, author_id, content, created_at, updated_at
FROM messages
WHERE channel_id = $1
  AND ($2::bigint = 0 OR id < $2::bigint)
  AND ($3::bigint = 0 OR id > $3::bigint)
ORDER BY id DESC
LIMIT $4
`

type GetChannelMessagesParams struct {
	ChannelID  int64 `json:"channel_id"`
	BeforeID   int64 `json:"before_id"`
	AfterID    int64 `json:"after_id"`
	LimitCount int32 `json:"limit_count"`
}

func (q *Queries) GetChannelMessages(ctx context.Context, arg GetChannelMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getChannelMessages,
		arg.ChannelID,
		arg.BeforeID,
		arg.AfterID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
