// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: guilds.proto

package guilds

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChannelMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     int64                  `protobuf:"varint,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelMembersRequest) Reset() {
	*x = GetChannelMembersRequest{}
	mi := &file_guilds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelMembersRequest) ProtoMessage() {}

func (x *GetChannelMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guilds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelMembersRequest.ProtoReflect.Descriptor instead.
func (*GetChannelMembersRequest) Descriptor() ([]byte, []int) {
	return file_guilds_proto_rawDescGZIP(), []int{0}
}

func (x *GetChannelMembersRequest) GetChannelId() int64 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

type GetChannelMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelMembersResponse) Reset() {
	*x = GetChannelMembersResponse{}
	mi := &file_guilds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelMembersResponse) ProtoMessage() {}

func (x *GetChannelMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guilds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelMembersResponse.ProtoReflect.Descriptor instead.
func (*GetChannelMembersResponse) Descriptor() ([]byte, []int) {
	return file_guilds_proto_rawDescGZIP(), []int{1}
}

func (x *GetChannelMembersResponse) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_guilds_proto protoreflect.FileDescriptor

const file_guilds_proto_rawDesc = "" +
	"\n" +
	"\fguilds.proto\x12\x06guilds\"9\n" +
	"\x18GetChannelMembersRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\x03R\tchannelId\"6\n" +
	"\x19GetChannelMembersResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds2i\n" +
	"\rGuildsService\x12X\n" +
	"\x11GetChannelMembers\x12 .guilds.GetChannelMembersRequest\x1a!.guilds.GetChannelMembersResponseB@Z>github.com/jakottelaar/relay-microservices/shared/proto/guildsb\x06proto3"

var (
	file_guilds_proto_rawDescOnce sync.Once
	file_guilds_proto_rawDescData []byte
)

func file_guilds_proto_rawDescGZIP() []byte {
	file_guilds_proto_rawDescOnce.Do(func() {
		file_guilds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guilds_proto_rawDesc), len(file_guilds_proto_rawDesc)))
	})
	return file_guilds_proto_rawDescData
}

var file_guilds_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_guilds_proto_goTypes = []any{
	(*GetChannelMembersRequest)(nil),  // 0: guilds.GetChannelMembersRequest
	(*GetChannelMembersResponse)(nil), // 1: guilds.GetChannelMembersResponse
}
var file_guilds_proto_depIdxs = []int32{
	0, // 0: guilds.GuildsService.GetChannelMembers:input_type -> guilds.GetChannelMembersRequest
	1, // 1: guilds.GuildsService.GetChannelMembers:output_type -> guilds.GetChannelMembersResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_guilds_proto_init() }
func file_guilds_proto_init() {
	if File_guilds_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guilds_proto_rawDesc), len(file_guilds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guilds_proto_goTypes,
		DependencyIndexes: file_guilds_proto_depIdxs,
		MessageInfos:      file_guilds_proto_msgTypes,
	}.Build()
	File_guilds_proto = out.File
	file_guilds_proto_goTypes = nil
	file_guilds_proto_depIdxs = nil
}
