// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: guilds.proto

package guilds

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GuildsService_GetChannelMembers_FullMethodName = "/guilds.GuildsService/GetChannelMembers"
)

// GuildsServiceClient is the client API for GuildsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuildsServiceClient interface {
	GetChannelMembers(ctx context.Context, in *GetChannelMembersRequest, opts ...grpc.CallOption) (*GetChannelMembersResponse, error)
}

type guildsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGuildsServiceClient(cc grpc.ClientConnInterface) GuildsServiceClient {
	return &guildsServiceClient{cc}
}

func (c *guildsServiceClient) GetChannelMembers(ctx context.Context, in *GetChannelMembersRequest, opts ...grpc.CallOption) (*GetChannelMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChannelMembersResponse)
	err := c.cc.Invoke(ctx, GuildsService_GetChannelMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuildsServiceServer is the server API for GuildsService service.
// All implementations must embed UnimplementedGuildsServiceServer
// for forward compatibility.
type GuildsServiceServer interface {
	GetChannelMembers(context.Context, *GetChannelMembersRequest) (*GetChannelMembersResponse, error)
	mustEmbedUnimplementedGuildsServiceServer()
}

// UnimplementedGuildsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuildsServiceServer struct{}

func (UnimplementedGuildsServiceServer) GetChannelMembers(context.Context, *GetChannelMembersRequest) (*GetChannelMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChannelMembers not implemented")
}
func (UnimplementedGuildsServiceServer) mustEmbedUnimplementedGuildsServiceServer() {}
func (UnimplementedGuildsServiceServer) testEmbeddedByValue()                       {}

// UnsafeGuildsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuildsServiceServer will
// result in compilation errors.
type UnsafeGuildsServiceServer interface {
	mustEmbedUnimplementedGuildsServiceServer()
}

func RegisterGuildsServiceServer(s grpc.ServiceRegistrar, srv GuildsServiceServer) {
	// If the following call pancis, it indicates UnimplementedGuildsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GuildsService_ServiceDesc, srv)
}

func _GuildsService_GetChannelMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuildsServiceServer).GetChannelMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuildsService_GetChannelMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuildsServiceServer).GetChannelMembers(ctx, req.(*GetChannelMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuildsService_ServiceDesc is the grpc.ServiceDesc for GuildsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuildsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "guilds.GuildsService",
	HandlerType: (*GuildsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChannelMembers",
			Handler:    _GuildsService_GetChannelMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guilds.proto",
}
