// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	Avatar    pgtype.Text        `json:"avatar"`
	Bio       pgtype.Text        `json:"bio"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
