// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSessions = `-- name: CountActiveSessions :one
SELECT COUNT(*) FROM user_sessions 
WHERE user_account_id = $1 
  AND revoked_at IS NULL 
  AND expires_at > NOW()
`

func (q *Queries) CountActiveSessions(ctx context.Context, userAccountID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessions, userAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO user_accounts (
    id,
    email,
    password_hash
) VALUES (
    $1, $2, $3
)
RETURNING id, email, password_hash, last_login_at, created_at, updated_at
`

type CreateAccountParams struct {
	ID           int64  `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.ID, arg.Email, arg.PasswordHash)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (id, user_account_id, refresh_token_hash, user_agent, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_account_id, refresh_token_hash, user_agent, ip_address, expires_at, revoked_at, last_used_at, created_at
`

type CreateSessionParams struct {
	ID               int64              `json:"id"`
	UserAccountID    int64              `json:"user_account_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	IpAddress        *netip.Addr        `json:"ip_address"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserAccountID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM user_accounts
WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, password_hash, last_login_at, created_at, updated_at FROM user_accounts
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, password_hash, last_login_at, created_at, updated_at FROM user_accounts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccountByID(ctx context.Context, id int64) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_account_id, refresh_token_hash, user_agent, ip_address, expires_at, revoked_at, last_used_at, created_at FROM user_sessions 
WHERE refresh_token_hash = $1 
  AND revoked_at IS NULL 
  AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, refreshTokenHash string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, refreshTokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE user_sessions 
SET revoked_at = NOW()
WHERE user_account_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userAccountID int64) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userAccountID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE user_sessions 
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE user_accounts
SET last_login_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE user_accounts
SET password_hash = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdatePasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.PasswordHash, arg.ID)
	return err
}

const updateSessionLastUsed = `-- name: UpdateSessionLastUsed :exec
UPDATE user_sessions 
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateSessionLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateSessionLastUsed, id)
	return err
}
