// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID        int64              `json:"id"`
	GuildID   int64              `json:"guild_id"`
	Name      string             `json:"name"`
	Topic     pgtype.Text        `json:"topic"`
	Type      int16              `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Guild struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Icon        pgtype.Text        `json:"icon"`
	OwnerID     int64              `json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GuildMember struct {
	GuildID  int64              `json:"guild_id"`
	UserID   int64              `json:"user_id"`
	Nick     pgtype.Text        `json:"nick"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}
