// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"
)

type Querier interface {
	CreateGuild(ctx context.Context, arg CreateGuildParams) (Guild, error)
	GetGuild(ctx context.Context, id int64) (Guild, error)
}

var _ Querier = (*Queries)(nil)
